### sign in request
POST http://localhost:3001/api/v1/sign_in
X-Requested-With: XMLHttpRequest
content-type: application/json

{
  "email":  "test9999@gmail.com",
  "password": "testu9999"
}

### sign up request
POST http://localhost:3001/api/v1/sign_up
X-Requested-With: XMLHttpRequest
content-type: application/json

{
  "nickname": "test9999",
  "email":  "test9999@gmail.com",
  "password": "testtest"
}